ALTER TABLE solver_profile ADD COLUMN eight_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN coxed_four_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN four_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN quad_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN pair_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN double_bias INTEGER NOT NULL DEFAULT 0;
ALTER TABLE solver_profile ADD COLUMN single_bias INTEGER NOT NULL DEFAULT 0;
