CREATE TABLE solver_profile (
    id              INTEGER PRIMARY KEY NOT NULL,
    team_id         INTEGER NOT NULL,
    name            TEXT    NOT NULL,
    description     TEXT,
    skill_variance_weight       INTEGER NOT NULL,
    pair_affinity_weight        INTEGER NOT NULL,
    seat_affinity_weight        INTEGER NOT NULL,
    side_preference_weight      INTEGER NOT NULL,
    weight_class_slack_weight   INTEGER NOT NULL,
    cox_cooldown_penalty        INTEGER NOT NULL,
    placement_reward_weight     INTEGER NOT NULL,
    pair_strength_weight        INTEGER NOT NULL,
    bow_pair_strength_weight    INTEGER NOT NULL,
    height_balance_weight       INTEGER NOT NULL,
    end_pair_skill_weight       INTEGER NOT NULL,
    engine_room_strength_weight INTEGER NOT NULL,
    partial_fill_bonus          INTEGER NOT NULL,
    non_scull_retention_weight  INTEGER NOT NULL,
    bow_cox_fit_weight          INTEGER NOT NULL,
    FOREIGN KEY (team_id) REFERENCES team(id) ON DELETE CASCADE,
    UNIQUE (team_id, name)
);
