// @generated by hand; regenerate with `diesel print-schema` when the migration changes.

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    rower (id) {
        id -> Integer,
        name -> Text,
        email -> Nullable<Text>,
        weight_class -> RowerWeightClassMapping,
        skill -> SkillMapping,
        strength -> StrengthMapping,
        height -> HeightMapping,
        side -> SideMapping,
        side_strength -> Integer,
        can_scull -> Integer,
        can_cox -> Integer,
        is_designated_cox -> Integer,
        active -> Integer,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        user_id -> Nullable<Integer>,
    }
}

diesel::table! {
    app_user (id) {
        id -> Integer,
        email -> Text,
        password_hash -> Nullable<Text>,
        name -> Text,
        status -> Text,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        opt_in_reminders -> Integer,
        opt_in_lineups -> Integer,
    }
}

diesel::table! {
    user_role (user_id) {
        user_id -> Integer,
        role -> Text,
    }
}

diesel::table! {
    user_invite (token_hash) {
        token_hash -> Text,
        user_id -> Integer,
        expires_at -> Timestamp,
    }
}

diesel::table! {
    magic_link (token_hash) {
        token_hash -> Text,
        user_id -> Integer,
        redirect_path -> Text,
        expires_at -> Timestamp,
        created_at -> Timestamp,
        team_id -> Nullable<Integer>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    boat (id) {
        id -> Integer,
        name -> Text,
        weight_class -> WeightClassMapping,
        seat_count -> Integer,
        has_cox -> Integer,
        oars_per_seat -> Integer,
        acquired_at -> Nullable<Date>,
        manufactured_at -> Nullable<Date>,
        relinquished_at -> Nullable<Date>,
        stroke_side -> SideMapping,
        cox_position -> CoxPositionMapping,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    rower_seat_affinity (rower_id, zone) {
        rower_id -> Integer,
        zone -> SeatZoneMapping,
        weight -> Integer,
    }
}

diesel::table! {
    pair_affinity (rower_a_id, rower_b_id) {
        rower_a_id -> Integer,
        rower_b_id -> Integer,
        weight -> Integer,
    }
}

diesel::table! {
    team (id) {
        id -> Integer,
        name -> Text,
        created_at -> Timestamp,
        self_edit_level -> Text,
        default_practice_time -> Nullable<Time>,
    }
}

diesel::table! {
    team_membership (team_id, rower_id) {
        team_id -> Integer,
        rower_id -> Integer,
    }
}

diesel::table! {
    team_coach (team_id, user_id) {
        team_id -> Integer,
        user_id -> Integer,
    }
}

diesel::table! {
    team_boat_default (team_id, boat_id) {
        team_id -> Integer,
        boat_id -> Integer,
    }
}

diesel::table! {
    practice (id) {
        id -> Integer,
        team_id -> Integer,
        date -> Date,
        notes -> Nullable<Text>,
        cancelled -> Integer,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    availability (rower_id, team_id, date) {
        rower_id -> Integer,
        team_id -> Integer,
        date -> Date,
        status -> AvailabilityStatusMapping,
    }
}

diesel::table! {
    lineup (id) {
        id -> Integer,
        practice_id -> Integer,
        boat_id -> Integer,
        created_at -> Timestamp,
    }
}

diesel::table! {
    lineup_seat (lineup_id, seat_position) {
        lineup_id -> Integer,
        seat_position -> Integer,
        rower_id -> Integer,
        is_cox -> Integer,
    }
}

diesel::table! {
    solver_profile (id) {
        id -> Integer,
        team_id -> Integer,
        name -> Text,
        description -> Nullable<Text>,
        skill_variance_weight -> Integer,
        pair_affinity_weight -> Integer,
        seat_affinity_weight -> Integer,
        side_preference_weight -> Integer,
        weight_class_slack_weight -> Integer,
        cox_cooldown_penalty -> Integer,
        placement_reward_weight -> Integer,
        pair_strength_weight -> Integer,
        bow_pair_strength_weight -> Integer,
        height_balance_weight -> Integer,
        end_pair_skill_weight -> Integer,
        engine_room_strength_weight -> Integer,
        partial_fill_bonus -> Integer,
        non_scull_retention_weight -> Integer,
        bow_cox_fit_weight -> Integer,
        top_boat_stacking_weight -> Integer,
        pair_eligibility_weight -> Integer,
        minimize_bench_weight -> Integer,
        boat_size_stacking_weight -> Integer,
        bench_cooldown_penalty -> Integer,
        eight_bias -> Integer,
        coxed_four_bias -> Integer,
        four_bias -> Integer,
        quad_bias -> Integer,
        pair_bias -> Integer,
        double_bias -> Integer,
        single_bias -> Integer,
    }
}

diesel::table! {
    sync_source (id) {
        id -> Integer,
        team_id -> Integer,
        source_type -> Text,
        config -> Text,
        last_synced_at -> Nullable<Timestamp>,
        last_error -> Nullable<Text>,
        created_at -> Timestamp,
        poll_interval_minutes -> Nullable<Integer>,
    }
}

diesel::table! {
    email_log (id) {
        id -> Integer,
        team_id -> Integer,
        email_type -> Text,
        practice_date -> Date,
        sent_at -> Timestamp,
        recipient_count -> Integer,
        sent_by_user_id -> Integer,
    }
}

diesel::table! {
    audit_log (id) {
        id -> Integer,
        timestamp -> Timestamp,
        user_id -> Nullable<Integer>,
        action -> Text,
        resource_type -> Text,
        resource_id -> Text,
        detail -> Nullable<Text>,
    }
}

diesel::joinable!(audit_log -> app_user (user_id));
diesel::joinable!(sync_source -> team (team_id));
diesel::joinable!(solver_profile -> team (team_id));
diesel::joinable!(rower_seat_affinity -> rower (rower_id));
diesel::joinable!(rower -> app_user (user_id));
diesel::joinable!(user_role -> app_user (user_id));
diesel::joinable!(user_invite -> app_user (user_id));
diesel::joinable!(magic_link -> app_user (user_id));
diesel::joinable!(email_log -> team (team_id));
diesel::joinable!(availability -> rower (rower_id));
diesel::joinable!(availability -> team (team_id));
diesel::joinable!(practice -> team (team_id));
diesel::joinable!(team_membership -> team (team_id));
diesel::joinable!(team_membership -> rower (rower_id));
diesel::joinable!(team_coach -> team (team_id));
diesel::joinable!(team_boat_default -> team (team_id));
diesel::joinable!(team_boat_default -> boat (boat_id));
diesel::joinable!(lineup -> practice (practice_id));
diesel::joinable!(lineup -> boat (boat_id));
diesel::joinable!(lineup_seat -> lineup (lineup_id));
diesel::joinable!(lineup_seat -> rower (rower_id));

diesel::allow_tables_to_appear_in_same_query!(
    audit_log,
    rower,
    boat,
    rower_seat_affinity,
    pair_affinity,
    team,
    team_membership,
    team_coach,
    team_boat_default,
    practice,
    availability,
    lineup,
    lineup_seat,
    app_user,
    user_role,
    user_invite,
    magic_link,
    email_log,
    solver_profile,
    sync_source,
);
