// @generated by hand; regenerate with `diesel print-schema` when the migration changes.

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    rower (id) {
        id -> Integer,
        name -> Text,
        weight_class -> RowerWeightClassMapping,
        skill -> SkillMapping,
        strength -> StrengthMapping,
        height -> HeightMapping,
        side -> SideMapping,
        side_strength -> Integer,
        sweep_bias -> Integer,
        can_cox -> Integer,
        is_designated_cox -> Integer,
        active -> Integer,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        weight_kg -> Nullable<Double>,
        height_m -> Nullable<Double>,
        first_name -> Nullable<Text>,
        last_name -> Nullable<Text>,
    }
}

diesel::table! {
    erg_test (id) {
        id -> Integer,
        rower_id -> Integer,
        distance_m -> Integer,
        time_cs -> Integer,
        rowed_at -> Nullable<Date>,
        created_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    app_user (id) {
        id -> Integer,
        email -> Text,
        password_hash -> Nullable<Text>,
        name -> Text,
        status -> UserStatusMapping,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        opt_in_reminders -> Integer,
        opt_in_lineups -> Integer,
        rower_id -> Nullable<Integer>,
        opt_in_stale_alerts -> Integer,
        first_name -> Nullable<Text>,
        last_name -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    user_role (user_id) {
        user_id -> Integer,
        role -> RoleMapping,
    }
}

diesel::table! {
    user_invite (token_hash) {
        token_hash -> Text,
        user_id -> Integer,
        expires_at -> Timestamp,
    }
}

diesel::table! {
    magic_link (token_hash) {
        token_hash -> Text,
        user_id -> Integer,
        redirect_path -> Text,
        expires_at -> Timestamp,
        created_at -> Timestamp,
        team_id -> Nullable<Integer>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    boat (id) {
        id -> Integer,
        name -> Text,
        weight_class -> WeightClassMapping,
        seat_count -> Integer,
        has_cox -> Integer,
        oars_per_seat -> Integer,
        acquired_at -> Nullable<Date>,
        manufactured_at -> Nullable<Date>,
        relinquished_at -> Nullable<Date>,
        stroke_side -> SideMapping,
        cox_position -> CoxPositionMapping,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    rower_seat_affinity (rower_id, zone) {
        rower_id -> Integer,
        zone -> SeatZoneMapping,
        weight -> Integer,
    }
}

diesel::table! {
    pair_affinity (rower_a_id, rower_b_id) {
        rower_a_id -> Integer,
        rower_b_id -> Integer,
        weight -> Integer,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    team (id) {
        id -> Integer,
        name -> Text,
        created_at -> Timestamp,
        default_practice_time -> Nullable<Time>,
        default_practice_duration_minutes -> Nullable<Integer>,
        archived -> Integer,
        default_practice_days -> Nullable<Integer>,
        assume_available -> Integer,
        erg_threshold_distance_m -> Nullable<Integer>,
        bucket_visibility -> BucketVisibilityMapping,
        member_raw_metrics -> Integer,
    }
}

diesel::table! {
    team_threshold (team_id, metric) {
        team_id -> Integer,
        metric -> Text,
        low_mid -> Double,
        mid_high -> Double,
        high_very -> Double,
    }
}

diesel::table! {
    team_membership (team_id, rower_id) {
        team_id -> Integer,
        rower_id -> Integer,
    }
}

diesel::table! {
    team_coach (team_id, user_id) {
        team_id -> Integer,
        user_id -> Integer,
    }
}

diesel::table! {
    team_boat_default (team_id, boat_id) {
        team_id -> Integer,
        boat_id -> Integer,
    }
}

diesel::table! {
    practice (id) {
        id -> Integer,
        team_id -> Integer,
        date -> Date,
        time -> Nullable<Time>,
        notes -> Nullable<Text>,
        cancelled -> Integer,
        duration_minutes -> Nullable<Integer>,
        timeline_json -> Nullable<Text>,
        plan_dismissed -> Integer,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    availability (rower_id, practice_id) {
        rower_id -> Integer,
        practice_id -> Integer,
        status -> AvailabilityStatusMapping,
    }
}

diesel::table! {
    lineup (id) {
        id -> Integer,
        practice_id -> Integer,
        boat_id -> Integer,
        created_at -> Timestamp,
        is_draft -> Integer,
    }
}

diesel::table! {
    lineup_seat (lineup_id, seat_position) {
        lineup_id -> Integer,
        seat_position -> Integer,
        rower_id -> Integer,
        is_cox -> Integer,
    }
}

diesel::table! {
    solver_profile (id) {
        id -> Integer,
        team_id -> Integer,
        name -> Text,
        description -> Nullable<Text>,
        skill_variance_weight -> Integer,
        pair_affinity_weight -> Integer,
        seat_affinity_weight -> Integer,
        side_preference_weight -> Integer,
        weight_class_slack_weight -> Integer,
        cox_cooldown_penalty -> Integer,
        placement_reward_weight -> Integer,
        pair_strength_weight -> Integer,
        bow_pair_strength_weight -> Integer,
        height_balance_weight -> Integer,
        end_pair_skill_weight -> Integer,
        engine_room_strength_weight -> Integer,
        partial_fill_bonus -> Integer,
        non_scull_retention_weight -> Integer,
        bow_cox_fit_weight -> Integer,
        top_boat_stacking_weight -> Integer,
        pair_eligibility_weight -> Integer,
        minimize_bench_weight -> Integer,
        boat_size_stacking_weight -> Integer,
        bench_cooldown_penalty -> Integer,
        stroke_spread_weight -> Integer,
        eight_bias -> Integer,
        coxed_four_bias -> Integer,
        four_bias -> Integer,
        quad_bias -> Integer,
        pair_bias -> Integer,
        double_bias -> Integer,
        single_bias -> Integer,
    }
}

diesel::table! {
    sync_source (id) {
        id -> Integer,
        team_id -> Integer,
        source_type -> Text,
        config -> Text,
        last_synced_at -> Nullable<Timestamp>,
        last_error -> Nullable<Text>,
        created_at -> Timestamp,
        poll_interval_minutes -> Nullable<Integer>,
    }
}

diesel::table! {
    email_log (id) {
        id -> Integer,
        team_id -> Integer,
        email_type -> Text,
        practice_date -> Date,
        sent_at -> Timestamp,
        recipient_count -> Integer,
        sent_by_user_id -> Integer,
    }
}

diesel::table! {
    audit_log (id) {
        id -> Integer,
        timestamp -> Timestamp,
        user_id -> Nullable<Integer>,
        action -> Text,
        resource_type -> Text,
        resource_id -> Text,
        detail -> Nullable<Text>,
    }
}

diesel::table! {
    stale_digest_log (id) {
        id -> Integer,
        last_sent_at -> Timestamp,
    }
}

diesel::table! {
    lineup_notification (id) {
        id -> Integer,
        practice_id -> Integer,
        rower_id -> Integer,
        sent_at -> Timestamp,
    }
}

diesel::table! {
    onboarding_progress (app_user_id, step) {
        app_user_id -> Integer,
        step -> Text,
        completed_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    oar_set (id) {
        id -> Integer,
        name -> Text,
        oar_count -> Integer,
        notes -> Nullable<Text>,
        active -> Integer,
        created_at -> Timestamp,
        oar_type -> OarTypeMapping,
    }
}

diesel::table! {
    oar_set_preference (id) {
        id -> Integer,
        oar_set_id -> Integer,
        boat_id -> Integer,
        priority -> Integer,
    }
}

diesel::table! {
    practice_boat_oars (id) {
        id -> Integer,
        practice_id -> Integer,
        boat_id -> Integer,
        oar_set_id -> Integer,
    }
}

diesel::joinable!(onboarding_progress -> app_user (app_user_id));
diesel::joinable!(oar_set_preference -> oar_set (oar_set_id));
diesel::joinable!(oar_set_preference -> boat (boat_id));
diesel::joinable!(practice_boat_oars -> practice (practice_id));
diesel::joinable!(practice_boat_oars -> boat (boat_id));
diesel::joinable!(practice_boat_oars -> oar_set (oar_set_id));
diesel::joinable!(audit_log -> app_user (user_id));
diesel::joinable!(team_threshold -> team (team_id));
diesel::joinable!(sync_source -> team (team_id));
diesel::joinable!(solver_profile -> team (team_id));
diesel::joinable!(erg_test -> rower (rower_id));
diesel::joinable!(rower_seat_affinity -> rower (rower_id));
diesel::joinable!(app_user -> rower (rower_id));
diesel::joinable!(user_role -> app_user (user_id));
diesel::joinable!(user_invite -> app_user (user_id));
diesel::joinable!(magic_link -> app_user (user_id));
diesel::joinable!(email_log -> team (team_id));
diesel::joinable!(availability -> rower (rower_id));
diesel::joinable!(availability -> practice (practice_id));
diesel::joinable!(practice -> team (team_id));
diesel::joinable!(team_membership -> team (team_id));
diesel::joinable!(team_membership -> rower (rower_id));
diesel::joinable!(team_coach -> team (team_id));
diesel::joinable!(team_boat_default -> team (team_id));
diesel::joinable!(team_boat_default -> boat (boat_id));
diesel::joinable!(lineup -> practice (practice_id));
diesel::joinable!(lineup -> boat (boat_id));
diesel::joinable!(lineup_seat -> lineup (lineup_id));
diesel::joinable!(lineup_seat -> rower (rower_id));
diesel::joinable!(lineup_notification -> practice (practice_id));
diesel::joinable!(lineup_notification -> rower (rower_id));

diesel::allow_tables_to_appear_in_same_query!(
    audit_log,
    erg_test,
    rower,
    boat,
    rower_seat_affinity,
    pair_affinity,
    team,
    team_membership,
    team_coach,
    team_boat_default,
    team_threshold,
    practice,
    availability,
    lineup,
    lineup_seat,
    app_user,
    user_role,
    user_invite,
    magic_link,
    email_log,
    solver_profile,
    sync_source,
    lineup_notification,
    stale_digest_log,
    onboarding_progress,
    oar_set,
    oar_set_preference,
    practice_boat_oars,
);
