// @generated by hand; regenerate with `diesel print-schema` when the migration changes.

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    rower (id) {
        id -> Integer,
        name -> Text,
        email -> Nullable<Text>,
        weight_class -> RowerWeightClassMapping,
        skill -> SkillMapping,
        strength -> StrengthMapping,
        height -> HeightMapping,
        side -> SideMapping,
        side_strength -> Integer,
        can_scull -> Integer,
        can_cox -> Integer,
        is_designated_cox -> Integer,
        active -> Integer,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        user_id -> Nullable<Integer>,
    }
}

diesel::table! {
    app_user (id) {
        id -> Integer,
        email -> Text,
        password_hash -> Nullable<Text>,
        name -> Text,
        status -> Text,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::table! {
    user_role (user_id) {
        user_id -> Integer,
        role -> Text,
    }
}

diesel::table! {
    user_invite (token_hash) {
        token_hash -> Text,
        user_id -> Integer,
        expires_at -> Timestamp,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    boat (id) {
        id -> Integer,
        name -> Text,
        weight_class -> WeightClassMapping,
        seat_count -> Integer,
        has_cox -> Integer,
        oars_per_seat -> Integer,
        acquired_at -> Nullable<Date>,
        manufactured_at -> Nullable<Date>,
        relinquished_at -> Nullable<Date>,
        stroke_side -> SideMapping,
        cox_position -> CoxPositionMapping,
    }
}

diesel::table! {
    rower_seat_affinity (rower_id, seat_position) {
        rower_id -> Integer,
        seat_position -> Integer,
        weight -> Integer,
    }
}

diesel::table! {
    pair_affinity (rower_a_id, rower_b_id) {
        rower_a_id -> Integer,
        rower_b_id -> Integer,
        weight -> Integer,
    }
}

diesel::table! {
    team (id) {
        id -> Integer,
        name -> Text,
        created_at -> Timestamp,
    }
}

diesel::table! {
    team_membership (team_id, rower_id) {
        team_id -> Integer,
        rower_id -> Integer,
    }
}

diesel::table! {
    team_coach (team_id, user_id) {
        team_id -> Integer,
        user_id -> Integer,
    }
}

diesel::table! {
    practice (id) {
        id -> Integer,
        team_id -> Integer,
        date -> Date,
        notes -> Nullable<Text>,
    }
}

diesel::table! {
    use diesel::sql_types::*;
    use crate::sql_types::*;

    availability (rower_id, team_id, date) {
        rower_id -> Integer,
        team_id -> Integer,
        date -> Date,
        status -> AvailabilityStatusMapping,
    }
}

diesel::table! {
    lineup (id) {
        id -> Integer,
        practice_id -> Integer,
        boat_id -> Integer,
        created_at -> Timestamp,
    }
}

diesel::table! {
    lineup_seat (lineup_id, seat_position) {
        lineup_id -> Integer,
        seat_position -> Integer,
        rower_id -> Integer,
        is_cox -> Integer,
    }
}

diesel::joinable!(rower_seat_affinity -> rower (rower_id));
diesel::joinable!(rower -> app_user (user_id));
diesel::joinable!(user_role -> app_user (user_id));
diesel::joinable!(user_invite -> app_user (user_id));
diesel::joinable!(availability -> rower (rower_id));
diesel::joinable!(availability -> team (team_id));
diesel::joinable!(practice -> team (team_id));
diesel::joinable!(team_membership -> team (team_id));
diesel::joinable!(team_membership -> rower (rower_id));
diesel::joinable!(team_coach -> team (team_id));
diesel::joinable!(lineup -> practice (practice_id));
diesel::joinable!(lineup -> boat (boat_id));
diesel::joinable!(lineup_seat -> lineup (lineup_id));
diesel::joinable!(lineup_seat -> rower (rower_id));

diesel::allow_tables_to_appear_in_same_query!(
    rower,
    boat,
    rower_seat_affinity,
    pair_affinity,
    team,
    team_membership,
    team_coach,
    practice,
    availability,
    lineup,
    lineup_seat,
    app_user,
    user_role,
    user_invite,
);
